# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dj < Formula
  desc "DJ — an AI coding harness TUI for OpenAI Codex"
  homepage "https://github.com/robinojw/dj"
  version "0.1.5"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robinojw/dj/releases/download/v0.1.5/dj_0.1.5_darwin_amd64.tar.gz"
      sha256 "ce7019b0783e2923ea8229a581f379dc0974fe98f64b6e63c435ba3762c638b4"

      define_method(:install) do
        bin.install "dj"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robinojw/dj/releases/download/v0.1.5/dj_0.1.5_darwin_arm64.tar.gz"
      sha256 "1707414a370756f786db830e3f9169ccbbcc8eaec473c746d9b7668363acc5ed"

      define_method(:install) do
        bin.install "dj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinojw/dj/releases/download/v0.1.5/dj_0.1.5_linux_amd64.tar.gz"
      sha256 "cde8e2e027ebcafeb860928b288ba1e681b447ab66d10e889c9f66e5f7cd84cf"
      define_method(:install) do
        bin.install "dj"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinojw/dj/releases/download/v0.1.5/dj_0.1.5_linux_arm64.tar.gz"
      sha256 "bc89f55d302b21fa82b9dc4439c6301efe7a94f9b87e7bb99611e3774bb9f21c"
      define_method(:install) do
        bin.install "dj"
      end
    end
  end

  test do
    system "#{bin}/dj", "--version"
  end
end
