# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dj < Formula
  desc "DJ — an AI coding harness TUI for OpenAI Codex"
  homepage "https://github.com/robinojw/dj"
  version "0.1.6"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robinojw/dj/releases/download/v0.1.6/dj_0.1.6_darwin_amd64.tar.gz"
      sha256 "60a7fe6f86c6639996a85b1ab66de1a63c74dd4326795aeecfd810360717f5cd"

      define_method(:install) do
        bin.install "dj"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robinojw/dj/releases/download/v0.1.6/dj_0.1.6_darwin_arm64.tar.gz"
      sha256 "4033a5be6c6868d32c3a0a76621c8dec77f5648d00a2e0f99874c7dd15d79904"

      define_method(:install) do
        bin.install "dj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinojw/dj/releases/download/v0.1.6/dj_0.1.6_linux_amd64.tar.gz"
      sha256 "9a07f80089f02bb769b48d3df3b060881104475b25c75804e84d3414646e043c"
      define_method(:install) do
        bin.install "dj"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinojw/dj/releases/download/v0.1.6/dj_0.1.6_linux_arm64.tar.gz"
      sha256 "aa518b5f234b544d186e25e0175b525c073407d34294974e1dbb70e90f226efc"
      define_method(:install) do
        bin.install "dj"
      end
    end
  end

  test do
    system "#{bin}/dj", "--version"
  end
end
